lesson3/add migrations
Anna1327/TestGuru pull request #2
Opened 2022-01-06 05:47 UTC by Anna1327

2022-01-06 13:38 UTC, BubuntuClu requested changes

2022-01-06 13:38 UTC, BubuntuClu commented on db/migrate/20220105193710_create_tests.rb
> +
нужно добавить внешний ключ к таблице категорий

2022-01-06 13:38 UTC, BubuntuClu commented on db/migrate/20220106042618_create_questions.rb
> +
нужно добавить внешний ключ к таблице тестов

2022-01-06 13:38 UTC, BubuntuClu commented on db/migrate/20220106042722_create_answers.rb
> +
нужно добавить внешний ключ к таблице вопросов

2022-01-06 13:38 UTC, BubuntuClu commented on db/migrate/20220106051315_add_tests_ref_to_categories.rb
> +    add_reference :categories, :tests, foreign_key: true
неправильно указаны таблицы. связь добавилась не в ту таблицу.

2022-01-06 13:38 UTC, BubuntuClu commented on db/schema.rb
> +    t.integer "tests_id"
тут видно что столбец имеет неправильное название. комментарий был в задании по SQL. должно быть в единственном числе

2022-01-06 13:38 UTC, BubuntuClu commented on db/schema.rb
> +    t.integer "tests_id"
ну и сам столбец находится не в той таблице. должен быть столбец категорий в таблице тестов

2022-01-06 13:38 UTC, BubuntuClu commented on db/schema.rb
> +    t.integer "questions_id"
этот столбец тоже неправильный

2022-01-07 16:52 UTC, BubuntuClu approved these changes

2022-01-07 16:52 UTC, BubuntuClu commented on db/migrate/20220106042618_create_questions.rb
> +      t.integer :test_id, null: false
можно так сделать `t.references :test, foreign_key: true`
в этом случае будет создан столбец, индекс на этот столбец и внешний ключ. лучше использовать этот синтаксис когда есть возможность

2022-01-08 02:13 UTC, Anna1327 commented on db/migrate/20220106042618_create_questions.rb
> +      t.integer :test_id, null: false
исправила

2022-01-08 02:14 UTC, merged