Lesson4
Anna1327/TestGuru pull request #3
Opened 2022-01-08 11:27 UTC by Anna1327

2022-01-08 21:13 UTC, BubuntuClu requested changes

2022-01-08 21:13 UTC, BubuntuClu commented on db/migrate/20220105193710_create_tests.rb
> +      t.references :category, null: false, foreign_key: true
нельзя править миграции которые уже слиты мастер. такие изменения не будут применены у других разработчиков/прод серверов. нужно отменить изменения которые ты внесла и добавить их через новые миграции

2022-01-08 21:13 UTC, BubuntuClu commented on db/migrate/20220105193710_create_tests.rb
> +      t.references :author, null: false, foreign_key: { to_table: :users }
зачем это поле? за что оно будет отвечать?

2022-01-08 21:13 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User'
зачем добавлять автора? как он будет использоваться?

2022-01-10 08:30 UTC, Anna1327 commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User'
я подумала, что так можно будет узнать какой именно пользователь добавил/создал тест

2022-01-10 08:43 UTC, Anna1327 commented on db/migrate/20220105193710_create_tests.rb
> +      t.references :category, null: false, foreign_key: true
убрала, добавила новые миграции

2022-01-11 00:32 UTC, merged