add auth user, sessions
Anna1327/TestGuru pull request #9
Opened 2022-01-27 06:20 UTC by Anna1327

2022-01-27 06:50 UTC, BubuntuClu requested changes

2022-01-27 06:50 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:unauthenticated_url] = request.path
запоминать надо только если пользователь не авторизован. в другом случае он попадет куда хотел

2022-01-27 06:50 UTC, BubuntuClu commented on config/routes.rb
> +  get 'sessions/new'
дублирует путь на 12 строке

2022-01-27 06:50 UTC, BubuntuClu commented on db/migrate/20220106042850_create_users.rb
> -      t.string :firstName, null: false
нельзя править миграции, которые смержены в другую ветку. надо откатить это изменение и через новую миграцию создать это ограничение

2022-01-27 06:50 UTC, BubuntuClu commented on db/migrate/20220125024219_drop_table_tests_users.rb
> +    drop_table :user_tests, if_exists: true
тут так же. надо создать новую миграцию на удаление

2022-01-27 06:50 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, presence: true, format: { with: /\A(.+)@(.+)\.(.+)\z/ }
используй регулярку из модуля URI

2022-01-27 06:50 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, presence: true, format: { with: /\A(.+)@(.+)\.(.+)\z/ }
так же надо проверять уникальность почты(не забудь про индекс в БД)

2022-01-27 06:50 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :firstName, presence: true
`first_name`. используем snake-case в руби коде

2022-01-28 07:07 UTC, BubuntuClu requested changes

2022-01-28 07:07 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, presence: true, format: { with: CHECK_EMAIL }
`validates :email, presence: true, format: { with: CHECK_EMAIL }, uniqueness: true`

2022-01-28 07:07 UTC, BubuntuClu commented on db/migrate/20220127171437_add_index_to_email_users.rb
> +    add_index(:users, :email)
индекс должен быть уникальный

2022-01-28 07:07 UTC, BubuntuClu commented on db/migrate/20220127172745_add_col_name_in_user.rb
> +    add_column :users, :first_name, :string
а что тут за черная магия происходит?

2022-01-28 07:09 UTC, BubuntuClu requested changes

2022-01-28 07:09 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +    render 'sessions/alert', css_class: 'flash_alert' if flash[:alert]
ключ у флэш сообщения может быть не только `alert`. подставляй ключ из параметров, или делай перебор всех ключей в хэше флэша

2022-01-28 07:09 UTC, BubuntuClu commented on app/views/sessions/_alert.html.erb
> +<p class=<%= css_class %>>
это, видимо, уже неактуально и можно удалить

2022-01-28 17:10 UTC, Anna1327 commented on db/migrate/20220127172745_add_col_name_in_user.rb
> +    add_column :users, :first_name, :string
у меня в таблице поля firstName/lastName были в camelcase, нельзя использовать в руби-коде camelcase.
Я не знала как создавать юзера, если не сделать permit(:firstName)
Решила поменять названия колонок в бд с помощью миграции

2022-01-28 22:56 UTC, merged